### ISSUE TITLE
bds3 support

### ISSUE THREAD

**Issue by earth-obs** [YizeZhang/Net_Diff#8]
Hi,
In the Control_Net.txt file, I only see beidou satellites until C49. Is Net_Diff support all BDS3 satellites?  If not will you release a patch for it?
Thanks.

**Comment by YizeZhang** [comment]
Actually, **C47~C49** is **C59~C61**. I change it just to reduce the size of the matrix. So Net_Diff supports C01-C46 and C59-C61.

**Comment by earth-obs** [comment]
Thanks
